#!/bin/bash

function github.auth() {
    curl --request GET \
        --url "https://api.github.com/octocat" \
        --header "Authorization: Bearer $1" \
        --header "X-GitHub-Api-Version: 2022-11-28"
}
